### PR TITLE
DE-613:Delete docs.yaml file for Workiva/abide

### PR DESCRIPTION
**Pull request by geethatummala-wf**
## Motivation
 https://jira.atl.workiva.net/browse/DE-613

As part of, [Dev Portal Service deprecation](https://wiki.atl.workiva.net/display/DE/Poster+-+Dev+Portal+Discovery+2.0%3A+Discovery+and+Planning); removing the “docs.yml” file that’s been created to render repo docs on to the portal.

## Changes
 File paths included in `docs.yaml `of this repo will no longer be rendered/hosted on [Dev Portal](https://dev.workiva.net/docs/teams/platform/application-frameworks/libraries/abide) with the yaml file deletion.

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Client Platform member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/abide/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/abide/blob/master/CONTRIBUTING.md#manual-testing-criteria

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by robbecker-wf — APPROVED** [review]

**Comment by robbecker-wf** [comment]
+10 CI passing is sufficient

**Comment by robbecker-wf** [comment]
@Workiva/release-management-pp do your thing

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
