### PR TITLE
Improve the score on pub

### PR DESCRIPTION
**Pull request by robbecker-wf**
# Overview
Add a few things to improve the score on pub

# Changes
- Add a changelog
- Add an example of running abide
- Add authors

# Testing
- No code changes, so CI passing is sufficient

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by georgelesica-wf** [comment]
+1

**Comment by georgelesica-wf** [comment]
@Workiva/release-management-p

**Comment by teresarevious-wf** [comment]
RM +1 verified deps are being picked up on tag 1.6.4

**Pull request merged**
