### PR TITLE
remove smithy-runner-generator

### PR DESCRIPTION
**Pull request by josephswanson-wf**
@jeffhall-wk @stevenosborne-wf .. skynet is failing because this is dart 1.. I'd vote to approve skynet runs for these and mash merge

also, this PR isn't for vuln hunting.. I'm tired of finding these references in github searches

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by autobot-wf** [comment]
Skynet test results failed initially for this build but were approved by joseph.swanson
https://wf-skynet-hrd.appspot.com/apps/test/smithy/2116352/1

**Comment by josephswanson-wf** [comment]
@rmconsole-wf

**Comment by josephswanson-wf** [comment]
+1 QA tests pass

**Comment by josephswanson-wf** [comment]
@rmconsole-wf

**Comment by josephswanson-wf** [comment]
@Workiva/release-management-pp

**Pull request merged**
